# Generated by Django 4.2 on 2024-11-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='svg_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
